config/routes.rb
Rails.application.routes.draw do
     

  resources :comments
  resources :tutorings
	# on peut faire sa aussii resources :resumes, only: [:index, :new, :create, :destroy]
  #resources :admin 

  get '/users/all' => 'users#index' 
 
       
  #resources :visitor 
  
  root to: 'visitors#index'
  
  #resources :users
  
  devise_for :users, :path => 'accounts'
  get '/users' =>   'users#show', :as => :user_root
  get 'users/u_ads' => 'users#u_ads'
  resources :users do
    resources :ads
  end
  
  #resources :ads
  
  resources :ads
  get 'captcha'  =>   'ads#capstore'
  #post 'ads/:id' => 'ads#sellAdd'
  
  get 'books/new/:id' => 'books#createfromtemplate'
  resources :books
  
  get 'electronics/new/:id' => 'electronics#createfromtemplate'
  resources :electronics
  
  get 'tutorings/new/:id' => 'tutorings#createfromtemplate'
  resources :tutorings
  
  get 'workgroups/new/:id' => 'workgroups#createfromtemplate'
  resources :workgroups
 
  #resources :researches
  get    'r'       =>  'researches#index'
  get    'r_advc'  =>  'researches#newAdvanced'
  get    'r/:id'   =>  'researches#show'
  post   'new_r'   =>  'researches#create' 
  #resources :researches
  post   'mail'   =>  'ad_mailer#sendmail' 
  # try those later 
  get    'home'    => 'pages#home'
  get    'help'    => 'pages#help'
  get    'about'   => 'pages#about'
  get    'contact' => 'pages#contact'
  get    'book'    => 'books#index'

  
  
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
	belongs_to :ad
end

app/controllers/tutorings_controller.rb
class TutoringsController < ApplicationController
  before_action :set_tutoring, only: [:show, :edit, :update, :destroy]

  # GET /tutorings
  # GET /tutorings.json
  def index
    @tutorings = Tutoring.all
  end

  # GET /tutorings/1
  # GET /tutorings/1.json
  def show
  end

  # GET /tutorings/new
  def new
    checkUserIsLogedIn?
    @user = current_user
    @ad = Ad.new
    @tutoring = Tutoring.new
  end

  # GET /tutorings/1/edit
  def edit
  end
  
  def createfromtemplate
    checkUserIsLogedIn?
    @ad = Ad.find(params[:id]).clone
    @tutoring = @ad.tutoring.clone
    render "tutorings/new" 
  end 

  # POST /tutorings
  # POST /tutorings.json
  def create
    checkUserIsLogedIn?
    @ad = Ad.new()   
    @ad.title = params[:ad][:title]
    @ad.description = params[:ad][:description]
    @ad.price = params[:ad][:price]
    @ad.user = current_user
    @ad.tutoring = @tutoring = Tutoring.new
    @ad.attachment = params[:ad][:attachment]
    @ad.category = "tutoring"

    @tutoring.ad = @ad
    @tutoring.course = params[:tutoring][:course] 
    
    @ad.save
    @tutoring.save 

    respond_to do |format|
      if @tutoring.save
        format.html { redirect_to @tutoring, notice: 'Tutoring was successfully created.' }
        format.json { render :show, status: :created, location: @tutoring }
      else
        format.html { render :new }
        format.json { render json: @tutoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorings/1
  # PATCH/PUT /tutorings/1.json
  def update
    respond_to do |format|
      if @tutoring.update(tutoring_params)
        format.html { redirect_to @tutoring, notice: 'Tutoring was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutoring }
      else
        format.html { render :edit }
        format.json { render json: @tutoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorings/1
  # DELETE /tutorings/1.json
  def destroy
    @tutoring.destroy
    respond_to do |format|
      format.html { redirect_to tutorings_url, notice: 'Tutoring was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutoring
      @tutoring = Tutoring.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutoring_params
      params.fetch(:tutoring, {})
    end
end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/views/tutorings/_form.html.erb
<%= form_for( Tutoring.new ) do |f| %>

    <%= label :ad, :title %>
    <%= text_field :ad, :title %><br>
    <%= label :ad, :description %>
    <%= text_area :ad, :description %><br>
    <%= label :ad, :price %>
    <%= text_field :ad, :price %><br>
    <%= f.label :course %>
    <%= f.text_field :course %>

    <p>
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
    </p>
    
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tutorings/_render_ad.html.erb
<h4>course:</h4>
<p><%= @ad.tutoring.course %></p>

app/views/tutorings/edit.html.erb
<h1>Editing Tutoring</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutoring %> |
<%= link_to 'Back', tutorings_path %>

app/views/tutorings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tutorings</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorings.each do |tutoring| %>
      <tr>
        <td><%= tutoring.course %></td>
        <td><%= link_to 'Show', tutoring %></td>
        <td><%= link_to 'Edit', edit_tutoring_path(tutoring) %></td>
        <td><%= link_to 'Destroy', tutoring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutoring', new_tutoring_path %>

app/views/tutorings/new.html.erb
<h1>New Tutoring</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorings_path %>

app/views/tutorings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @tutoring.course %>
</p>

<%= link_to 'Edit', edit_tutoring_path(@tutoring) %> |
<%= link_to 'Back', tutorings_path %>