config/routes.rb
Rails.application.routes.draw do
     

  resources :comments
  resources :tutorings
	# on peut faire sa aussii resources :resumes, only: [:index, :new, :create, :destroy]
  #resources :admin 

  get '/users/all' => 'users#index' 
 
       
  #resources :visitor 
  
  root to: 'visitors#index'
  
  #resources :users
  
  devise_for :users, :path => 'accounts'
  get '/users' =>   'users#show', :as => :user_root
  get 'users/u_ads' => 'users#u_ads'
  resources :users do
    resources :ads
  end
  
  #resources :ads
  
  resources :ads
  get 'captcha'  =>   'ads#capstore'
  #post 'ads/:id' => 'ads#sellAdd'
  
  get 'books/new/:id' => 'books#createfromtemplate'
  resources :books
  
  get 'electronics/new/:id' => 'electronics#createfromtemplate'
  resources :electronics
  
  get 'tutorings/new/:id' => 'tutorings#createfromtemplate'
  resources :tutorings
  
  get 'workgroups/new/:id' => 'workgroups#createfromtemplate'
  resources :workgroups
 
  #resources :researches
  get    'r'       =>  'researches#index'
  get    'r_advc'  =>  'researches#newAdvanced'
  get    'r/:id'   =>  'researches#show'
  post   'new_r'   =>  'researches#create' 
  #resources :researches
  post   'mail'   =>  'ad_mailer#sendmail' 
  # try those later 
  get    'home'    => 'pages#home'
  get    'help'    => 'pages#help'
  get    'about'   => 'pages#about'
  get    'contact' => 'pages#contact'
  get    'book'    => 'books#index'

  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ads
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(current_user.id)
    authorize @user
  end

  def update
    @user = User.find(current_user.id)
    user = User.find(params[:id])
    authorize @user
    if user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def u_ads
    @user = User.find(current_user.id)
    authorize @user
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_nav_bar.html.erb
<div>           
  <%= link_to 'Account', edit_user_registration_path, {:class=>"menu-item"} %>
  <%= link_to 'My Ads', users_u_ads_path, {:class=>"menu-item"} %>
  <%= link_to 'New Ad', new_ad_path, {:class=>"menu-item"} %>

  <a class="menu-item" href="#">
    <span class="octicon octicon-radio-tower"></span>
    <span class="counter">3</span>
    Notifications
  </a>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/_user_adds.html.erb
		
<% @user.ads.each do |ad| %>
  <table  border="1">
    <tbody>
    <tr>

	<td>     
	    <%=  image_tag(ad.attachment, size: "80", alt: "No images") if ad.attachment?  %>
	</td>

	<td>
            <%= link_to ad.title, ad  %>
	    <p class=""> <%= ad.description %></p>
   	 </td>

	<td>
		<p class=""> <%= ad.price %> </p>
  </td>

	<td>
		<p class=""> <%= ad.sold || false %> </p>
	</td>

	<td>	
        <%= link_to 'Edit', edit_ad_path(ad), class: "btn btn-xs btn-warning" %>
        <%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-danger" %>
        <%= form_for :ad, url: ad_path(ad), method: :put  do |f| %>
          <%= f.text_field  :sold,:value => true,  :hidden => true %>
          <%= f.submit :value => "sold"%>
        <% end %>

  </td>

      </tr>
    </tbody>
  </table>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="/users" method="post">
   Email: <input type="text" name="email"><br>
   Password: <input type="text" name="password"><br>
 <input type="submit" value="Submit">
</form>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>
</div>

app/views/users/u_ads.html.erb
<div class="container">

<div class="colums">
	<div>
            <%= render 'user_adds' %>
	<%= link_to 'Back', users_path %>
	
	</div>
</div>

</div>