config/routes.rb
Rails.application.routes.draw do
     

  resources :comments
  resources :tutorings
	# on peut faire sa aussii resources :resumes, only: [:index, :new, :create, :destroy]
  #resources :admin 

  get '/users/all' => 'users#index' 
 
       
  #resources :visitor 
  
  root to: 'visitors#index'
  
  #resources :users
  
  devise_for :users, :path => 'accounts'
  get '/users' =>   'users#show', :as => :user_root
  get 'users/u_ads' => 'users#u_ads'
  resources :users do
    resources :ads
  end
  
  #resources :ads
  
  resources :ads
  get 'captcha'  =>   'ads#capstore'
  #post 'ads/:id' => 'ads#sellAdd'
  
  get 'books/new/:id' => 'books#createfromtemplate'
  resources :books
  
  get 'electronics/new/:id' => 'electronics#createfromtemplate'
  resources :electronics
  
  get 'tutorings/new/:id' => 'tutorings#createfromtemplate'
  resources :tutorings
  
  get 'workgroups/new/:id' => 'workgroups#createfromtemplate'
  resources :workgroups
 
  #resources :researches
  get    'r'       =>  'researches#index'
  get    'r_advc'  =>  'researches#newAdvanced'
  get    'r/:id'   =>  'researches#show'
  post   'new_r'   =>  'researches#create' 
  #resources :researches
  post   'mail'   =>  'ad_mailer#sendmail' 
  # try those later 
  get    'home'    => 'pages#home'
  get    'help'    => 'pages#help'
  get    'about'   => 'pages#about'
  get    'contact' => 'pages#contact'
  get    'book'    => 'books#index'

  
  
end

app/models/ad.rb
class Ad < ActiveRecord::Base
    belongs_to :user
    belongs_to :book
    belongs_to :electronic
    belongs_to :tutoring
	belongs_to :workgroup
    
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.

    self.inheritance_column = nil   # to overide STI


    def ad_type

    end
    

    def self.types
      [:all_categories] + reflect_on_all_associations(:belongs_to).map() {|x| x.name} - [:user] 
    end

    def self.all_sub
      (reflect_on_all_associations(:belongs_to)).map {|x| x.active_record.all}
    end


end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :ad
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ad
  belongs_to :user
end

app/models/electronic.rb
class Electronic < ActiveRecord::Base
	belongs_to :ad
end

app/models/research.rb
class Research < ActiveRecord::Base
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
	belongs_to :ad
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ads
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workgroup.rb
class Workgroup < ActiveRecord::Base
	belongs_to :ad
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /adds
  # GET /adds.json
  def index
    @ads = Ad.all
  end

  # GET /adds/1
  # GET /adds/1.json
  def show
  end

  # GET /adds/new
  def new
    checkUserIsLogedIn?
    @user = User.find(current_user.id)
  end

  # GET /adds/1/edit
  def edit
    checkUserIsLogedIn?
    @user = User.find(current_user.id)
    @ads = Ad.find(params[:id])
  end

  # POST /adds
  # POST /adds.json
  def create
    checkUserIsLogedIn?
    @user = User.find(params[:user_id])
    @ad = @user.ads.new(params.require(:ad).permit(:title, :description))
    #@ad.type = 'book' # we will change this in the futre
    @ad.save
    redirect_to user_path(@user)
  end

  # PATCH/PUT /adds/1
  # PATCH/PUT /adds/1.json
  def update
    checkUserIsLogedIn?
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Add was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adds/1
  # DELETE /adds/1.json
  def destroy
    checkUserIsLogedIn?
    @ad.destroy
    redirect_to user_path(@ad.user)

    #respond_to do |format|
    #  format.html { redirect_to adds_url, notice: 'Add was successfully destroyed.' }
    #  format.json { head :no_content }
    #end


  end

  def capstore
    render :inline => "<%= show_simple_captcha %>" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title,:description,:price,:attachment,:sold)
    end
end

app/helpers/ad_mailer_helper.rb
module AdMailerHelper
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def checkUserIsLogedIn?
    if 
      user_signed_in?
    else
      redirect_to new_user_session
    end
  end

end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workgroups_helper.rb
module WorkgroupsHelper
end

app/views/layouts/_nav_links_for_auth.html.erb
<%= link_to "Home", user_root_path %>
<%= link_to "search", r_path %>
<a href="/about">About</a>
<% if user_signed_in? %>
  <%= link_to 'Edit account', edit_user_registration_path %>
  <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <%= link_to 'Users', users_all_path %>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualSpacePlus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<header class="masthead">
    <%= render 'layouts/nav_links_for_auth' %>	 	
</header>

<div class="container">
<div class="columns docs-layout">
      
      <div class="one-fourth column">
	<nav class="menu docs-menu">
	   <%= render 'users/nav_bar' if user_signed_in? %>
      	</nav>
      </div>

      <div class="three-fourths column markdown-body"> 
          <%= yield %>
      </div>
      
</div>      
</div>

</body>
</html>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>